const ACTIONS_SEARCH_PANEL = Object.freeze({
  EMPRESAS_LIST: 'SEARCH_PANEL_EMPRESAS_LIST',
  OFICINAS_LIST: 'SEARCH_PANEL_OFICINAS_LIST',
  CAMPANIAS_LIST: 'SEARCH_PANEL_CAMPANIAS_LIST',
  ESTATUSES_LIST: 'SEARCH_PANEL_ESTATUSES_LIST',
  PERIODOS_LIST: 'SEARCH_PANEL_PERIODOS_LIST',
  DESTINOS_LIST: 'SEARCH_PANEL_DESTINOS_LIST',
  GESTORES_LIST: 'SEARCH_PANEL_GESTORES_LIST',
  //
  RESULT_LIST: 'SEARCH_PANEL_RESULT_LIST',
  RESULT_EMPTY_LIST: 'SEARCH_PANEL_RESULT_EMPTY_LIST',
  CLEANOUT_LIST: 'SEARCH_PANEL_CLEANOUT_LIST',
  //
  CLEANOUT_BUFFER: 'SEARCH_PANEL_CLEANOUT_BUFFER',
  FILL_BUFFER: 'SEARCH_PANEL_FILL_BUFFER',
})

export default ACTIONS_SEARCH_PANEL;
