//fetch
export const FETCH_MAPA_JNDI = 'FETCH_MAPA_JNDI';

export const FETCH_OFICINAS = 'FETCH_OFICINAS';

export const FETCH_CAMPANIAS = 'FETCH_CAMPANIAS';

export const FETCH_PERIODOS = 'FETCH_PERIODOS';

export const FETCH_PERSONA = 'FETCH_PERSONA';

export const FETCH_GESTORES = 'FETCH_GESTORES';

export const FETCH_ARBOL_CAMPANIAS = 'FETCH_ARBOL_CAMPANIAS';

export const FETCH_PROSPECTOS = 'FETCH_PROSPECTOS';

export const FETCH_CITAS = 'FETCH_CITAS';
//set
export const SET_GESTORES = 'SET_GESTORES';

export const SET_ARBOL_CAMPANIAS = 'SET_ARBOL_CAMPANIAS';

export const SET_PROSPECTOS = 'SET_PROSPECTOS';
//post
export const POST_GENERAR_GESTION_PROSPECTO = 'POST_GENERAR_GESTION_PROSPECTO';

export const POST_GENERAR_CIERRE_CITA = 'POST_GENERAR_CIERRE_CITA';

export const POST_AGREGAR_TELEFONOS_PERSONA = 'POST_AGREGAR_TELEFONOS_PERSONA';