const ACTIONS_DIALOG_NOTIFICATION_MODAL = Object.freeze({
  SET: 'ACTIONS_DIALOG_NOTIFICATION_MODAL_SET',
  INIT: 'ACTIONS_DIALOG_NOTIFICATION_MODAL_INIT',
  LOADING: 'ACTIONS_DIALOG_NOTIFICATION_MODAL_LOADING',
})

export default ACTIONS_DIALOG_NOTIFICATION_MODAL;
